### ISSUE TITLE
Opsgenie user removal wrong order

### ISSUE THREAD

**Issue by zonArt** [opsgenie/terraform-provider-opsgenie#184]
Hi there,

I've got some issue when trying to remove a user from an opsgenie_user resource when this user is also referenced as a team member or a participant to a schedule rotation

### Terraform Version
Terraform v0.12.29
+ provider.opsgenie v0.5.0

### Affected Resource(s)
- opsgenie_user
- opsgenie_schedule_rotation
- opsgenie_team

### Debug Output
```
  # opsgenie_team.teams["teamtest"] will be updated in-place
  ~ resource "opsgenie_team" "teams" {
        delete_default_resources = true
        description              = "Testing intgerations and stuff"
        id                       = "589b1cf3-8e6c-431d-80a5-a02951f2a45c"
        name                     = "teamtest"

        member {
            id   = "551eae0c-9c3f-4adb-afee-e3998fe6dd42"
            role = "admin"
        }
      ~ member {
          ~ id   = "6551164a-6344-48ee-a68e-6a0d9012d1cb" -> "4a3e014a-9fc6-4104-baa1-d303d5a4cb92"
            role = "user"
        }
      - member {
          - id   = "4a3e014a-9fc6-4104-baa1-d303d5a4cb92" -> null
          - role = "user" -> null
        }
    }

  # opsgenie_user.users["usertest"] will be destroyed
  - resource "opsgenie_user" "users" {
      - full_name = "User Test" -> null
      - id        = "6551164a-6344-48ee-a68e-6a0d9012d1cb" -> null
      - locale    = "fr_CH" -> null
      - role      = "Admin" -> null
      - timezone  = "Europe/Belgrade" -> null
      - username  = "user.test@example.com" -> null
    }

Plan: 0 to add, 10 to change, 1 to destroy.

Do you want to perform these actions in workspace "staging"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opsgenie_user.users["user.test@example.com"]: Destroying... [id=6551164a-6344-48ee-a68e-6a0d9012d1cb]

Error: Error occurred with Status code: 428, Message: User cannot be modified. Please remove it from teams: [teamtest], Took: 0.040000, RequestId: 6f3a73f1-19d2-488d-9559-4ec423ab5713
```

### Expected Behavior
Terraform should remove the user from the team(s) and the schedule rotation(s) and then remove the user

### Actual Behavior
An error occurs mentioning that the user is still part of team(s) and/or schedule rotation(s)

### Steps to Reproduce
1. Create a user with
2. Create a team and attach the user to it as a member
3. Remove the user from the tf file and remove the member in the team tf file

**Comment by zdcthomas** [comment]
I'm also trying to figure out the preferred way to do this, and I'm hitting the exact same problem.

**Comment by jaceq** [comment]
It might depend on your state definition. How are you referring to that user in schedule / team? can you post you state definition?
&nbsp;
&nbsp;
&nbsp;
[Interested in terraform? Check out my articles!](https://medium.com/@business_99069/my-terraform-articles-4804e54fe6d6)

**Comment by zonArt** [comment]
Sure:

users.yml
```yaml
usertest:
  email: usertest@example.com
  full_name: User Test
  role: Admin
  locale: fr_CH
  timezone: Europe/Belgrade
otherexample:
  email: otherexample@foobar.com
  full_name: Other Example
  role: User
  locale: en_US
  timezone: Asia/Kolkata
```

users.tf
```hcl
locals {
  users = yamldecode(file("users.yml"))
}

resource "opsgenie_user" "users" {
  for_each  = local.users
  username  = each.value.email
  full_name = each.value.full_name
  role      = each.value.role
  locale    = each.value.locale
  timezone  = each.value.timezone
}
```
teams.yml
```yaml
otherexample:
  description: Other example
  members:
    usertest@example.com: user
    otherexample@foobar.com: admin
teamtest:
  description: Teamtest
  members:
    usertest@example.com:user
```

teams.tf
```hcl
locals {
  teams = yamldecode(file("teams.yml"))
}

resource "opsgenie_team" "teams" {
  for_each                 = local.teams
  name                     = each.key
  description              = each.value.description
  delete_default_resources = true

  dynamic "member" {
    for_each = each.value.members
    content {
      id   = opsgenie_user.users[member.key].id
      role = member.value
    }
  }
}
```

schedule_rotations.yml
```yaml
rotationtest:
  start_date: '2019-08-05T05:30:00Z'
  schedule_id: teamtest_schedule
  participants:
  - otherexample@foobar.com
  - usertest@example.com
anotherrotation:
  start_date: '2020-07-19T22:00:00Z'
  schedule_id: otherexample_schedule
  participants:
  - otherexample@foobar.com
```

schedule_rotations.tf
```hcl
locals {
  schedule_rotations_file = yamldecode(file("schedule_rotations.yml"))
  schedule_rotations      = { for k, v in local.schedule_rotations_file : k => local.schedule_rotations_file[k] if v.participants != [] }
}

resource "opsgenie_schedule_rotation" "schedule_rotations" {
  for_each    = local.schedule_rotations
  name        = each.key
  start_date  = each.value.start_date
  length      = 1
  type        = "weekly"
  schedule_id = opsgenie_schedule.schedules[each.value.schedule_id].id
  dynamic "participant" {
    for_each = each.value.participants
    content {
      type = "user"
      id   = opsgenie_user.users[participant.value].id
    }
  }
}
```
schedules.yml
```yaml
otherexample_schedule:
  description: ""
  timezone: "Asia/Kolkata"
  owner_team_id: "otherexample"
  enabled: true

teamtest_schedule:
  description: ""
  timezone: "Europe/Paris"
  owner_team_id: "teamtest"
  enabled: true
```

schedules.tf
```hcl
locals {
  schedules = yamldecode(file("schedules.yml"))
}

resource "opsgenie_schedule" "schedules" {
  for_each      = local.schedules
  name          = each.key
  description   = each.value.description
  timezone      = each.value.timezone
  owner_team_id = opsgenie_team.teams[each.value.owner_team_id].id
  enabled       = each.value.enabled
}
```
