### ISSUE TITLE
Feature Request: Add opsgenie_account data source

### ISSUE THREAD

**Issue by deepbrook** [opsgenie/terraform-provider-opsgenie#312]
Hello!

I'd like to suggest adding a `opsgenie_account` data block to the provider. I'm currently using a python script to do this (http data source would do the trick too), which is a bit meh because I need to pass on the Opsgenie Access token to it.

The resource block does not need any inputs:

```hcl
data "opsgenie_account" "details" {}
```

And forwarding the API response's data object would be fine as well:
```yaml
# response
data: <- include this object's attributes as attributes on the data source
  name: opsgenie
  userCount: 1450
  plan:
    maxUserCount: 1500
    name: Enterprise
    isYearly: true
# Discard the rest
took: 0.084
requestId: "e5122017-f5c5-4681-88ec-84e2898a61ad"
```
So, accessing the attributes would yield the following
```bash
> data.opsgenie_account.details.userCount
1450
> data.opsgenie_account.details.name
opsgenie
> data.opsgenie_account.details.plan.maxUserCount
1500
> data.opsgenie_account.details.plan.name
Enterprise
> data.opsgenie_account.details.plan.isYearly
true
# Bonus points for calculating the remaining seats
> data.opsgenie_account.details.seatsLeft
50
```

### Why is this useful?

Currently, I have no way to check if I have seats left for users I want to create using the provider's blocks. This means, I will not be able to know whether or not I can actually create user accounts, until I apply my terraform plan.

While this data source does not take care of the problem itself, it makes solving it easier. It'd be magical if I could run a check using the data source as well, but I'm not sure if this is a valid feature for a data source (e.g. pass an argument `seats_required` and it fails if the desired seat count is less then what's available in the plan).

Cheers and thanks!

### Important Factoids
The Account API can be found here: https://docs.opsgenie.com/docs/account-api
